# Generated by Django 5.1.4 on 2024-12-17 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=2, unique=True)),
                ('version', models.CharField(max_length=2)),
            ],
            options={
                'unique_together': {('model_name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField()),
                ('registered_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='robots.registeredmodel')),
            ],
        ),
    ]
